# Generated by Django 2.2.12 on 2020-04-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('message', models.CharField(max_length=500)),
                ('time_of_creation', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='in_progress', max_length=25)),
                ('intent_image', models.ImageField(blank=True, max_length=512, null=True, upload_to='i/%Y/%m/%d/%H/%M/')),
            ],
        ),
        migrations.CreateModel(
            name='Scenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
